FROM node:4.6.1
MAINTAINER josemrivera@gmail.com

# Install nodemon for service reloading
RUN npm install -g nodemon

# Install node-inspector for debugging
RUN npm install -g node-inspector

VOLUME ["/blackbox"]

WORKDIR /blackbox

